### ISSUE TITLE
为了方便一下大家，方便弄个阿里云镜像到云市场吗？

### ISSUE THREAD

**Issue by ch19751116** [chenchuxin/apollo-docker#1]
非常感谢

**Comment by chenchuxin** [comment]
官方的你弄个镜像就可以了啊，我知道的镜像
daocloud：http://xxx.m.daocloud.io（注册后使用，比163快，推荐）
网易加速器：http://hub-mirror.c.163.com(稍微慢一点) 
官方中国加速器：https://registry.docker-cn.com 
ustc的镜像：https://docker.mirrors.ustc.edu.cn 


创建或修改 `/etc/docker/daemon.json` 文件，修改为如下形式 （请将 加速地址 替换为在加速器页面获取的专属地址），重启docker
```
{
    "registry-mirrors": [
        "加速地址"
    ]
}
```
